// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using webNET_Hits_backend_aspnet_project_2.Data;

#nullable disable

namespace webNET_Hits_backend_aspnet_project_2.Migrations
{
    [DbContext(typeof(AddressDbContext))]
    partial class AddressDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("webNET_Hits_backend_aspnet_project_2.Models.DbModels.AsAddrObj", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("id"));

                    b.Property<long>("changeid")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("enddate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("isactive")
                        .HasColumnType("integer");

                    b.Property<int>("isactual")
                        .HasColumnType("integer");

                    b.Property<string>("level")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("nextid")
                        .HasColumnType("bigint");

                    b.Property<Guid>("objectguid")
                        .HasColumnType("uuid");

                    b.Property<long>("objectid")
                        .HasColumnType("bigint");

                    b.Property<int>("opertypeid")
                        .HasColumnType("integer");

                    b.Property<long>("previd")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("startdate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("typename")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("updatedate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("id");

                    b.ToTable("as_addr_obj", "fias");
                });

            modelBuilder.Entity("webNET_Hits_backend_aspnet_project_2.Models.DbModels.AsAdmHierarchy", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("id"));

                    b.Property<string>("areacode")
                        .HasColumnType("text");

                    b.Property<long>("changeid")
                        .HasColumnType("bigint");

                    b.Property<string>("citycode")
                        .HasColumnType("text");

                    b.Property<DateTime>("enddate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("isactive")
                        .HasColumnType("integer");

                    b.Property<long>("nextid")
                        .HasColumnType("bigint");

                    b.Property<long>("objectid")
                        .HasColumnType("bigint");

                    b.Property<long>("parentobjid")
                        .HasColumnType("bigint");

                    b.Property<string>("path")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("placecode")
                        .HasColumnType("text");

                    b.Property<string>("plancode")
                        .HasColumnType("text");

                    b.Property<long>("previd")
                        .HasColumnType("bigint");

                    b.Property<string>("regioncode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("startdate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("streetcode")
                        .HasColumnType("text");

                    b.Property<DateTime>("updatedate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("id");

                    b.ToTable("as_adm_hierarchy", "fias");
                });

            modelBuilder.Entity("webNET_Hits_backend_aspnet_project_2.Models.DbModels.AsHouses", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("id"));

                    b.Property<string>("addnum1")
                        .HasColumnType("text");

                    b.Property<string>("addnum2")
                        .HasColumnType("text");

                    b.Property<int?>("addtype1")
                        .HasColumnType("integer");

                    b.Property<int?>("addtype2")
                        .HasColumnType("integer");

                    b.Property<long>("changeid")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("enddate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("housenum")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("housetype")
                        .HasColumnType("integer");

                    b.Property<int>("isactive")
                        .HasColumnType("integer");

                    b.Property<int>("isactual")
                        .HasColumnType("integer");

                    b.Property<long>("nextid")
                        .HasColumnType("bigint");

                    b.Property<Guid>("objectguid")
                        .HasColumnType("uuid");

                    b.Property<long>("objectid")
                        .HasColumnType("bigint");

                    b.Property<int>("opertypeid")
                        .HasColumnType("integer");

                    b.Property<long>("previd")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("startdate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("updatedate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("id");

                    b.ToTable("as_houses", "fias");
                });
#pragma warning restore 612, 618
        }
    }
}
